#include "LAPsystemPlot.h"

LAPsystemPlot::LAPsystemPlot(const char* baseName, const char* plName) {
	PlotName = new char[1+strlen(plName)];
	snprintf(PlotName, 1+strlen(plName), "%s", plName);
	BaseName = new char[1+strlen(baseName)];
	snprintf(BaseName, 1+strlen(baseName), "%s", baseName);
	dataLines = NULL;
	dataLineCount = 0;
	dataColCount = 0;
	plotCommand = new char[1000000];
	plotSubCommand = new char[100000];
	sprintf(plotSubCommand, "%s", "");

	xLogScale = yLogScale = false;
	xLabel = new char[1024];
		sprintf(xLabel, "x");
	yLabel = new char[1024];
		sprintf(yLabel, "y");
	caption = new char[1024];
		sprintf(caption, "Caption");
	title = new char[1024];
		sprintf(title, "%s", "");
	plotTitle = new char[1024];
		sprintf(plotTitle, "%s", "");
	xSize = ySize = 1.0;
	pointSize = 1.0;
	usingStr = new char[1024];
		sprintf(usingStr, "1:2");

	lineWidth = 1;
	xRangeMin = INFINITY;
	xRangeMax = INFINITY;
	yRangeMin = INFINITY;
	yRangeMax = INFINITY;
	xErrorBars = false;
	yErrorBars = false;
	pointType = 1;
	lineType = -1;

	plotCmdCount = 0;
}


LAPsystemPlot::~LAPsystemPlot() {
	delete[] PlotName;
	delete[] BaseName;
	delete[] plotCommand;
	delete[] plotSubCommand;
	delete[] xLabel;
	delete[] yLabel;
	delete[] caption;
	delete[] title;
	delete[] plotTitle;
	delete[] usingStr;

	for (int i = 0; i < dataLineCount; i++) {
		delete[] dataLines[i];
		dataLines[i] = NULL;
	}
	delete[] dataLines;
	dataLines = NULL;
}


void LAPsystemPlot::setPlotData(int datLinCnt, int datColCnt, double** dat) {
	if (datLinCnt != 0 && datColCnt != 0 && dat != NULL) {
		dataLineCount = datLinCnt;
		dataColCount = datColCnt;
		dataLines = new double*[dataLineCount];
		for (int i = 0; i < dataLineCount; i++) {
			dataLines[i] = new double[dataColCount];
			for (int j = 0; j < dataColCount; j++) {
				dataLines[i][j] = dat[i][j];
			}
		}
	}
}

bool LAPsystemPlot::writeDataToFile(char* fileName) {
	bool res = false;
	if (fileName != NULL) {
		if (dataLineCount > 0 && dataColCount > 0 && dataLines != NULL) {
			FILE* dataFile = fopen(fileName, "w");
			if(dataFile != NULL) {
				for (int i = 0; i < dataLineCount; i++) {
					for(int j = 0; j < dataColCount; j++) {
						fprintf(dataFile, "%1.15e\t", dataLines[i][j]);
					}
					fprintf(dataFile, "\n");
				}
				fclose(dataFile);
				res = true;
			}
		}

	}
	return res;
}

void LAPsystemPlot::writePlotFilesToDisk(char* baseDirectoryName) {
	char* str = new char[2048];

	sprintf (str, "%s/plots/%s_%s.dat", baseDirectoryName, BaseName, PlotName);
	writeDataToFile(str);

	sprintf(plotCommand,"# Plot automatically generated by LAPsystem\n\n");

	sprintf(str, "set xlabel \"%s\"\n", xLabel);
	strcat(plotCommand, str);

	sprintf(str, "set ylabel \"%s\"\n", yLabel);
	strcat(plotCommand, str);

	sprintf(str, "set title \"%s\"\n", plotTitle);
	strcat(plotCommand, str);

        sprintf(str, "set size square\n");
        strcat(plotCommand, str);

	if (isfinite(xRangeMin) || isfinite(xRangeMax)) {
		if (isinf(xRangeMin) && isfinite (xRangeMax))
			sprintf(str, "set xrange [*:%1.5f]\n", xRangeMax);
		else if (isfinite(xRangeMin) && isinf(xRangeMax))
			sprintf(str, "set xrange [%1.5f:*]\n", xRangeMin);
		else if (isfinite(xRangeMin) && isfinite(xRangeMax))
			sprintf(str, "set xrange [%1.5f:%1.5f]\n", xRangeMin, xRangeMax);
		strcat(plotCommand, str);
	}

	if (isfinite(yRangeMin) || isfinite(yRangeMax)) {
		if (isinf(yRangeMin) && isfinite (yRangeMax))
			sprintf(str, "set yrange [*:%1.5f]\n", yRangeMax);
		else if (isfinite(yRangeMin) && isinf(yRangeMax))
			sprintf(str, "set yrange [%1.5f:*]\n", yRangeMin);
		else if (isfinite(yRangeMin) && isfinite(yRangeMax))
			sprintf(str, "set yrange [%1.5f:%1.5f]\n", yRangeMin, yRangeMax);
		strcat(plotCommand, str);
	}

	strcat(plotCommand, plotSubCommand);


	char* pltScriptFileName = new char[2048];
	sprintf (pltScriptFileName, "%s/plots/%s_%s.gnu", baseDirectoryName, BaseName, PlotName);
	FILE* pltScriptFile = fopen(pltScriptFileName, "w");
	if (pltScriptFile != NULL) {
		fprintf (pltScriptFile, "%s",plotCommand);
		fclose(pltScriptFile);
	}
	delete[] pltScriptFileName;
	delete[] str;
}

void LAPsystemPlot::plotData(const char* usingStr) {
	char* plotSubCmd = new char[10000];
	char* str = new char[2048];
	sprintf(plotSubCmd, "%s\n", "# Plot command");


	char* plotCaption = new char[2048];
	if(caption != NULL)
		sprintf(plotCaption, "%s", caption);
	else
		sprintf(plotCaption, "%s", usingStr);

	if (xLogScale || yLogScale) {
		sprintf(str, "set logscale ");
		if (xLogScale)
			strcat(str, "x");
		if (yLogScale)
			strcat(str, "y");
		strcat(str, "\n");
		strcat(plotSubCmd, str);
	}

	sprintf(str, "set size %1.1f,%1.1f\n", xSize, ySize);
	strcat(plotSubCmd, str);

	sprintf(str, "set pointsize %1.2f\n", pointSize);
	strcat(plotSubCmd, str);

// 	sprintf(str, "set style line 5 lt %d lw %d pt %d\n", lineType, lineWidth, pointType);
// 	strcat(plotSubCmd, str);

	if(plotCmdCount == 0)
		sprintf(str, "plot '%s_%s.dat' using %s ", BaseName, PlotName, usingStr);
	else
		sprintf(str, "replot '%s_%s.dat' using %s ", BaseName, PlotName, usingStr);
	if (xErrorBars|| yErrorBars) {
		strcat(str, "with ");
		if (xErrorBars && !yErrorBars)
			strcat(str, "xerrorbars ");
		else if (yErrorBars && !xErrorBars)
			strcat(str, "yerrorbars ");
		else if (yErrorBars && xErrorBars)
			strcat(str, "xyerrorbars ");
	}
	strcat(plotSubCmd, str);
	sprintf(str, "title \"%s\"\n", title);
	strcat(plotSubCmd, str);

	strcat(plotSubCommand, plotSubCmd);
	plotCmdCount++;

	delete[] str;
	str = NULL;
	delete[] plotSubCmd;
	plotSubCmd = NULL;
	delete[] plotCaption;
	plotCaption = NULL;
}

void LAPsystemPlot::setXLogScale(bool on) {
	xLogScale = on;
}

void LAPsystemPlot::setYLogScale(bool on) {
	yLogScale = on;
}

void LAPsystemPlot::setXLabel(const char* label) {
	strcpy(xLabel, label);
}

void LAPsystemPlot::setYLabel(const char* label) {
	strcpy(yLabel, label);
}

void LAPsystemPlot::setCaption(const char* label) {
	strcpy(caption, label);
}

void LAPsystemPlot::setSize(double x, double y) {
//	xSize = x;
//	ySize = y;
}

void LAPsystemPlot::setPointSize(double size) {
	pointSize = size;
}

void LAPsystemPlot::setLineWidth(int width) {
	lineWidth = width;
}

void LAPsystemPlot::setXRange(double min, double max) {
	xRangeMin = min;
	xRangeMax = max;
}

void LAPsystemPlot::setYRange(double min, double max) {
	yRangeMin = min;
	yRangeMax = max;
}

void LAPsystemPlot::setXErrorBars(bool on) {
	xErrorBars = on;
}

void LAPsystemPlot::setYErrorBars(bool on) {
  yErrorBars = on;
}

void LAPsystemPlot::setPointType(int type) {
	pointType = type;
}

void LAPsystemPlot::setLineType(int type) {
	lineType = type;
}

void LAPsystemPlot::setTitle(const char* title) {
	strcpy(this->title, title);
}

void LAPsystemPlot::setPlotTitle(const char* title) {
	strcpy(plotTitle, title);
}

void LAPsystemPlot::plotDirect(const char* plotCmd) {
	if (plotCmd != NULL && strlen(plotCmd) != 0) {
		// Makro replacement:
		char* FILE_replacement = new char[strlen(BaseName) + strlen(PlotName) +8];
		sprintf(FILE_replacement, "'%s_%s.dat'", BaseName, PlotName);
		char* new_plotCmd = new char[strlen(plotCmd)*strlen(FILE_replacement)];
		strcpy(new_plotCmd, plotCmd);
		str_replace(new_plotCmd, "FILE", FILE_replacement);

		strcat(plotSubCommand, new_plotCmd);
		appendEndLine(plotSubCommand);

		delete[] FILE_replacement;
		delete[] new_plotCmd;
	}
}

char* LAPsystemPlot::getPlotScriptFileNamePrefix() {
	char* fileName = new char[strlen(BaseName) + strlen(PlotName) + 2];
	sprintf(fileName, "%s_%s", BaseName, PlotName);
	return fileName;
}

char* LAPsystemPlot::getCaption() {
	char* resultStr = new char[strlen(caption)+1];
	strcpy(resultStr, caption);
	return resultStr;
}

void LAPsystemPlot::appendEndLine(char* str) {
	char* tmp = strrchr(str, '\0');
	if(*(tmp-1) != '\n') {
		*tmp = '\n';
		*(++tmp) = '\0';
	}
	tmp = NULL;
}

void LAPsystemPlot::str_replace(char* str, const char* token, const char* replacement) {
	if (str != NULL && strlen(str) != 0 && token != NULL && strlen(token) != 0) {
		char* new_rest = new char[strlen(replacement) + strlen(str) + 1];
		char* curr_pointer = str;
		char* split_point = NULL;

		while ((split_point = strstr(curr_pointer, token)) != NULL ) {
			char* after_token = split_point + strlen(token);
			sprintf(new_rest, "%s%s", replacement, after_token);
			strcpy(split_point, new_rest);
			curr_pointer = after_token;
		}
		delete[] new_rest;
	}
}
