#define xSSE_ExtremeFFT4D_Read2DSliceAndDoFirstAndSecond2DFFTStepBase2_InputSlidePrefetchCMD prefetch
#define xSSE_ExtremeFFT4D_Read2DSliceAndDoFirstAndSecond2DFFTStepBase2_InputSlidePrefetchUSE
#define xSSE_ExtremeFFT4D_Read2DSliceAndDoFirstAndSecond2DFFTStepBase2_OutputSlidePrefetchCMD prefetchw
#define xSSE_ExtremeFFT4D_Read2DSliceAndDoFirstAndSecond2DFFTStepBase2_OutputSlidePrefetchUSE
#define xSSE_ExtremeFFT4D_DoTwo2DFFTStepsBase2_SlidePrefetchCMD prefetchw
#define xSSE_ExtremeFFT4D_DoTwo2DFFTStepsBase2_SlidePrefetchUSE
#define xSSE_ExtremeFFT4D_Write2DSlice_SlideWriteCMD movnti
#define xSSE_ExtremeFFT4D_Read2DSliceAndDoFirstSecondAndThird1DD2FFTStepBase2_InputSlidePrefetchCMD prefetch
#define xSSE_ExtremeFFT4D_Read2DSliceAndDoFirstSecondAndThird1DD2FFTStepBase2_InputSlidePrefetchUSE
#define xSSE_ExtremeFFT4D_Read2DSliceAndDoFirstSecondAndThird1DD2FFTStepBase2_OutputSlidePrefetchCMD prefetchw
#define xSSE_ExtremeFFT4D_Read2DSliceAndDoFirstSecondAndThird1DD2FFTStepBase2_OutputSlidePrefetchUSE
#define xSSE_ExtremeFFT4D_DoFirstSecondAndThird1DD1FFTStepBase2_SlidePrefetchCMD prefetchw
#define xSSE_ExtremeFFT4D_DoFirstSecondAndThird1DD1FFTStepBase2_SlidePrefetchUSE
